name: Run Checks

on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          cache: gradle
          distribution: 'temurin'
      - name: Check with Gradle
        run: ./gradlew check --continue
